### ISSUE TITLE
Response did not include principalId

### ISSUE THREAD

**Issue by ryancarville** [nlang/serverless-offline-local-authorizers-plugin#5]
Hello,
I feel like I am close here but running into the following error. I am returning results.Payload.
```
Serverless: Running Authorization function for get /users (λ: $__LOCAL_AUTHORIZER_mylocalAuthProxyFn)
Printed results from invoke: 
{ StatusCode: 200,
  ExecutedVersion: '$LATEST',
  Payload:
       '{
        "principalId":"user",
        "policyDocument":{
            "Version":"2012-10-17",
            "Statement":[
                {
                 "Action":"execute-api:Invoke",
                 "Effect":"Deny",
                 "Resource":"arn:aws:execute-api:eu-central-1:my-AWS-Acct-ID:*"
                }
            ]
        },
    "context":{
        "platformRoles":"Guest",
        "userId":"unknown"
        }
    }' 
}
Serverless: Authorization response did not include a principalId: (λ: $__LOCAL_AUTHORIZER_mylocalAuthProxyFn)
```

**Comment by nlang** [comment]
Just return whats inside your `Payload` as an object and you should be fine.

**Comment by ryancarville** [comment]
Hey nlang.  Thanks for the reply.  When I do the following i get the below error.  And Postman/Browser hangs up.  I don't have a callback either.  Just a promise.
```
const AWS = require('aws-sdk');
const mylocalAuthProxyFn = async (event, context) => {
  console.log(event);
  const lambda = new AWS.Lambda();
  const req = {
    FunctionName: 'my-func-name',
    InvocationType: 'RequestResponse',
    Payload: JSON.stringify(event)
  };
  const results = await lambda.invoke(req).promise();
  if (results.StatusCode === 200) {
    return JSON.parse(results.Payload);
  }
  throw new Error('Unauthorized');
};

module.exports = { mylocalAuthProxyFn };

```

```
Serverless: Warning: Auth function '$__LOCAL_AUTHORIZER_mylocalAuthProxyFn' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.
```

Also don't know if this is related but on start up it returns this error but the `serverless.yml` functions are set correctly and when a endpoint tries to local authorizes the `local-authorizers.js` runs.
```
serverless-offline-local-authorizers-plugin: Invlalid or unknown local authorizer 'undefined'
```

**Comment by nlang** [comment]
Can't tell from the info you gave me, but if it hangs then probably you don't return a promise from the authorizer function or it never resolves. This is the minimal authorizer that must work, try that and when you get it working try adding your logic.

Also make sure the authorizer config in your serverless.yml is correct, especially that the `name` corresponds to your export.

```
const myAuthFn = async (event, context) => {

  return {
    principalId: "foo",
    policyDocument: {
      Version: "2012-10-17",
      Statement: [{
        Action: "execute-api:invoke",
        Effect: "Allow",
        Resource: "*"
      }]
    }
  };

};

module.exports = { myAuthFn };
```

**Comment by ryancarville** [comment]
That's the thing.  It does return the proper response from the authorizer function (see below).  And my config is correct I believe.  
congif
```
getCause:
    handler: functions/index.getCause
    events:
      - http:
          path: causes/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: Authorizer1
          localAuthorizer:       
            name: mylocalAuthProxyFn
            type: request

            
```
Response
```
{ principalId: 'user',
  policyDocument: { 
    Version: '2012-10-17', 
    Statement: [ [Object] ] },
  context: { platformRoles: 'Guest', userId: 'unknown' } }
```

**Comment by nlang** [comment]
I added an example, you can check it out here [https://github.com/nlang/serverless-offline-local-authorizers-plugin/blob/master/examples/simple](https://github.com/nlang/serverless-offline-local-authorizers-plugin/blob/master/examples/simple)

I think your `serverless.yml` has wrong indentation for `localAuthorizer`.

**Comment by ryancarville** [comment]
OK so I made the indentation changes but still getting the `Invalid or unknown authorizer 'undefined'`.
However, I removed all the AWS invoke calls and just returning a predefined object it works.  Not ideal though.  Why is it rejecting the promise?  I see the promise being returned in the correct format from the shared authroizer lambda.
So can you not return a response from a AWS.lambda.invoke()? 

localAuthFn - with AWS invoke
```
const AWS = require('aws-sdk');
const mylocalAuthProxyFn = async (event, context) => {
  const lambda = new AWS.Lambda();
  const req = {
    FunctionName: 'aidonic-endpoints-dev-createAuthorization',
    InvocationType: 'RequestResponse',
    Payload: JSON.stringify(event)
  };
  const result = await lambda.invoke(req).promise();
  if (result.StatusCode === 200) {
    const obj = JSON.parse(result.Payload);
    console.log(obj);
    console.log({
      principalId: obj.principalId,
      policyDocument: obj.policyDocument,
      context: obj.context
    });
    return obj;
  }
  throw new Error('Unauthorized');
};

module.exports = { mylocalAuthProxyFn };
```
locaAuthFn - predefined object return
```
const mylocalAuthProxyFn = async (event, context) => {
  return {
    principalId: 'user',
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: 'Allow',
          Resource: '*'
        }
      ]
    },
    context: {
      platformRoles: 'Guest',
      userId: 'unknown'
    }
  };
};

module.exports = { mylocalAuthProxyFn };
```

**Comment by nlang** [comment]
It doesn't matter where the data comes from, can be a lambda invocation, HTTP call or whatever you want. But you have to make sure that you return a promise that resolves to an object in the correct format for API Gateway. Maybe use a debugger to find out where and why it goes sideways. I'm pretty sure it is not a problem with the plugin though, I use it myself to invoke a deployed lambda that is used as authorizer.

**Comment by ryancarville** [comment]
Sounds good.  Thank you again for all your help!  You helped me move this forward!  It is working for the most part.  Just not getting the expected returns from the shared lambda but will look into it.  Excellent plugin!  Thank you!
