### ISSUE TITLE
Serverless offline local-authorizers not triggering start hook from serverless offline start

### ISSUE THREAD

**Issue by HuEric** [nlang/serverless-offline-local-authorizers-plugin#6]
Hello,

I'm using this plugin for our local authorizer, but I noticed it doesn't trigger `start` hook from serverless offline.
That's a bit bothering, as I also use s3-local, which start from the hook.

Any solution to also trigger `start` hook ?

Thank you

**Comment by nlang** [comment]
Hm, are you sure about this? See here: https://github.com/nlang/serverless-offline-local-authorizers-plugin/blob/d9bf540dba5fbd43efaee7b2de2dcfceefc07883/src/lib/AwsLocalAuthorizersPlugin.ts#L30

To be honest, to be absolutely sure I would have to look into the sls event/hook system and sls-offline as this is not what I  deal with on a daily basis. Feel free to submit a PR if you're more familiar with this.

**Comment by nlang** [comment]
I'm closing this. Feel free to re-open if there are any new insights.
